---
title: "Exam 2 Review"
format:
  html: default
  pdf: default
---

1.  Greg borrowed \$1,000 from a bank on Feb 02, 2024 at a simple interest rate of 5.5%.

    a)  How much interest does he owe if he pays back the money on Dec 21, 2024? Use the *Banker's Rule*. \vspace{1.5in} <br><br>
    b)  How much interest would Greg owe if we use *ordinary interest*?\vspace{1.5in}<br><br>

2.  On Oct 01, 2024, your credit card balance was \$690. On Nov 01, 2024, your credit card company will charge you an interest of \$45 if the balance is unpaid. What is the simple *interest rate* being charged?\clearpage<br><br>

3.  Sophia opened a CD account some time back and deposited \$65,000 at a simple interest rate of 4.99%. On Nov 17, 2024, her money had grown by \$1,100. Find the date when Sophia opened the account. Be sure to use the *Banker's Rule*. \vspace{2.5in}<br><br>

4.  You take a loan of \$1,000 on Jan 15, 2024, and the due date is Dec 15, 2024. The simple interest rate is 6.5%. Find the total amount due on the due date. \vspace{2in}<br><br>

5.  Amie and John estimate that they want to buy a house for \$ 250,000 and they want to make a down payment of 12.5% on the house. If they have 27 months to save for the down payment, how much should they invest in an account earning 3.9% interest compounded monthly so that they reach their goal? \clearpage<br><br>

6.  A toy store owner would like to borrow \$35,000 to increase her stock. The bank will give the owner a loan at an interest rate of 9.5% compounded weekly. How much will the owner end up paying if she pays back the loan in 3 years? \vspace{2.2in}<br><br>

7.  Terry invests \$5,000 in an account that earns 4.5% compounded weekly for 3 years and thereafter earns 5.5% compounded monthly. How much money will Terry have after 8 years? \vspace{2.2in}<br><br>

8.  Which investment is better: an investment that earns 5.5% compounded quarterly or an investment that earns 5.4% compounded monthly? Explain/show all work. \clearpage<br><br>

9.  Calculate the inflation rate between Feb, 2021 and Feb 2023. Suppose that in Feb 2021, Mustafa invested \$10,000 in an account that earned 4.5% compounded monthly and that the maturity date for the investment is Feb, 2023. Does this investment beat inflation? \vspace{3in}<br><br>

10. When Stacy was born in 2005, her parents got cash gifts that amounted to \$5,000. They decided to open an account for Stacy and deposit all the money. The fixed interest rate on the account was 6.99% compounded monthly. How much will Stacy have when she turns 18? When you account for inflation, was the investment profitable? Explain how you know.
